"""Original research synthesis. Raw third-party material is not redistributed."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sources = []
def source(id, title, author, date, lang, kind, access, url, locator, finding, caution, family):
    sources.append(dict(id=id,title=title,author=author,date=date,language=lang,kind=kind,access=access,url=url,locator=locator,finding=finding,caution=caution,family=family))

source('S01','Resolution on the return of the Romanian national treasure','European Parliament','2024-03-14','English','Official record','Full web text read','https://www.europarl.europa.eu/doceo/document/TA-9-2024-0171_EN.html','P9_TA(2024)0171; recitals D, I and paragraph 7','States the claim as 91.5 tonnes of fine gold; records partial cultural returns and the joint commission’s acknowledgement of authentic deposit documents.','A political resolution, not a court judgment, contemporary vault inspection, or recovery order.','Romanian official claim')
source('S02','The NBR treasure sent to Moscow — document portal','National Bank of Romania','2025-10-24 launch','English / Romanian','Archive portal','Portal and rendered sections read; selected scans inspected','https://www.bnr.ro/en/24945-the-nbr-treasure-sent-to-moscow','History and heritage; Romanian counterpart: 24788-tezaurul-bnr-evacuat-la-moscova','The bank announced inventories, historical images and copies of original documents from its own archive.','Initial text retrieval returned navigation; a subsequent browser pass reached the collection. Four selected protocol/annex photographs were visually inspected, not the complete archive. See S41–S43.','Romanian official claim')
source('S03','Cum arată Tezaurul României de la Moscova','Cristina Stancu, Adevărul, reproducing BNR material','2025-10-24','Romanian','News / official reprint','Full relevant web text read','https://adevarul.ro/economie/cum-arata-tezaurul-romaniei-de-la-moscova-2481879.html','Chronology; Prima restituire (1935); A doua restituire (1956)','Detailed shipment values and return procedures: 1935 via Odesa and Constanța; 1956 art, coins and medals, not the BNR reserve.','Same evidence family as BNR, not independent corroboration. Its two shipment values do not sum to its stated total; its 1956 category counts also differ from its headline total.','Romanian official claim')
source('S04','Tezaurul României la Moscova. 100 de ani mai târziu','National History Museum of Romania (MNIR)','2016-12-16','Romanian','Museum record','Full relevant web text read','https://www.mnir.ro/tezaurul-romaniei-la-moscova-100-de-ani-mai-tarziu/','Centenary exhibition announcement and appended governor’s remarks','Identifies Pietroasele as a returned, viewable treasure; says the National Art Museum’s 1956 return-inventory registers were exhibited. Lists what BNR actually received in 1935.','An exhibition announcement and quoted institutional address, not the underlying accession registers. Rounded gold totals here differ slightly from the current 91.5-tonne claim.','Romanian official claim')
source('S05','Destinul Tezaurului României. Argumente din arhivele ruse','Ilie Schipor; Oscar Print','2021','Romanian','Book','Publisher description and contents read','https://oscarprint.ro/magazin/destinul-tezaurului-romaniei-argumente-din-arhivele-ruse/','448 pp.; ISBN 978-973-668-550-7','Author’s reconstruction: partial evacuation in October 1919, return in July 1921, progressive expenditure from autumn 1921 through early 1925.','The full 448-page book was not obtained. The publisher’s summary is not a substitute for its document annexes.','Schipor archival reconstruction')
source('S06','Destinul Tezaurului României — publisher sample','Ilie Schipor','2021','Romanian / Russian','Book / document facsimile','16-page nonconsecutive preview inspected','https://oscarprint.ro/wp-content/uploads/2021/06/schw.pdf','Printed pp. 9–10, 30–31, 51–53, 64–65, 91–92, 105–106, 129–131','Includes the opening archival document and facsimiles: Bark to Alekseev, 28 October 1916, concerning the evacuation proposal.','Only a sample. It does not contain the decisive 1924 report, document 121. Citation given for document 1: RGVIA, f. 2003, op. 1, d. 1474, l. 221 recto/verso; original archive not visited.','Schipor archival reconstruction')
source('S07','Tezaurul BNR între Cazaciocul dezinformării și „Răsucita” româno-rusă (I)','Ilie Schipor interview / AFnews','2024-05-18','Romanian','Interview / research account','Written article read; embedded video not watched','https://afnews.ro/2024/05/18/prof-col-ilie-schipor-tezaurul-bancii-nationale-a-romaniei-intre-cazaciocul-dezinformarii-si-rasucita-romano-rusa-i/','Discussion comparing the 16 February 1917 inventory with the 23 May 1921 RGAE report','Schipor explicitly argues that the gold remained intact through May 1921, based on a denomination-by-denomination comparison.','The original May 1921 inventory and full comparison have not been independently audited. This is the researcher’s claim, not our own verified gram-level reconciliation.','Schipor archival reconstruction')
source('S08','„Soarta” sau „destinul” Tezaurului României','Ilie Schipor, Arhivele Totalitarismului','2022','Romanian','Scholarly article','Abstract and bibliographic record only','https://www.ceeol.com/search/article-detail?id=1083246','Vol. XXX, nos. 1–2, pp. 15–42','Abstract rejects several civil-war disappearance explanations and places final expenditure in the mid-1920s.','Full text requires access; not purchased or read. Same author and research family as S05–S07.','Schipor archival reconstruction')
source('S09','Romania’s Treasury — guarded by the Russian “ally”','Viorica Moisuc, Minerva','2022-02','English','Scholarly article / translated documents','Full PDF obtained; relevant passages read','https://editurafrm.ro/wp-content/uploads/2024/09/2-MOISUC.pdf','Vol. 2, issue 1, pp. 27–76; especially pp. 72–74 and notes 96–103','Reproduces a translated 13 December 1924 report describing 1919 relocations and subsequent overseas disposal of specified coin groups.','The URL’s 2024 upload date is not the publication date. Strongly polemical framing; translations are mediated through Schipor. The reproduced report contains an ambiguous numerical expression.','Schipor archival reconstruction')
source('S10','Судьба «румынского золота» в России 1916–2020. Очерки истории','Tatyana A. Pokivaylova, Aletheia / Institute of Slavic Studies RAS','2021','Russian','Book','Full 268-page PDF obtained; relevant chapters read','https://inslav.ru/sites/default/files/editions/2021pokivaylova.pdf','ISBN 978-5-00165-289-2; pp. 119–132, 143–167, 199–228, 243–253','Russian archival synthesis acknowledges gold still recorded in 1922 and described as обезличено by 1924; discusses inventories, returns and competing debt claims.','Some eastward routes are explicitly speculative. Two conflicting 1922 balances are quoted. “Depersonalized” does not by itself prove melting. Archive-access statements describe conditions when the book was written.','Pokivaylova / Russian historiography')
source('S11','Amintiri — including Jurnalul de la Moscova','Alexandru Lapedatu; edited by Ioan Opriș','1998 edition; diary 1917','Romanian','Published eyewitness diary','Full volume obtained; Moscow diary passages read','https://www.memorialsighet.ro/wp-content/uploads/2016/02/alapedatu_amintiri_opris_secured.pdf','Printed pp. 117–121, 129–130, 142, 151, 155–158; PDF page = printed page + 4','Day-by-day account of packing, departure, observed railway stops, damp storage, later relocation, and proposed evacuation to America.','Published transcription, not the handwritten notebook inspected. Lapedatu supervised cultural consignments, not an audit of all bullion. Download is for personal reading; this site does not redistribute the book.','Lapedatu eyewitness')
source('S12','Francis reports the Soviet retention of Romanian gold','US Ambassador David R. Francis to Secretary of State','1918-02-02','English','Contemporary diplomatic record','Full published document read','https://history.state.gov/historicaldocuments/frus1918Russiav02/d836','FRUS 1918, Russia vol. II, doc. 836; file 871.51/110','Contemporary US diplomatic evidence that the Soviet authorities held the gold and that Romania sought Allied intervention.','A diplomatic report, not a physical count. Its valuation must not be treated as a weighed gold quantity.','US diplomatic records')
source('S13','Further request for Allied protest over Romanian gold','US Ambassador David R. Francis','1918-02-07','English','Contemporary diplomatic record','Full published document read','https://history.state.gov/historicaldocuments/frus1918Russiav02/d838','FRUS 1918, Russia vol. II, doc. 838','Documents the immediate dispute and pressure for a formal Allied protest.','Shows diplomacy and contemporary knowledge; cannot establish the reserve’s later route.','US diplomatic records')
source('S14','Treasury explains treatment of Soviet gold and Swedish mint stamps','Assistant Secretary of the Treasury S. P. Gilbert Jr. to Assistant Secretary of State Fred M. Dearing','1921-03-25','English','Contemporary financial record','Full published document read','https://history.state.gov/historicaldocuments/frus1921v02/d724','FRUS 1921, vol. II, doc. 724; file 861.51/1002','Explains the distinction between gold suspected of Soviet origin and gold bearing the official stamp of a friendly country’s mint, including Sweden.','Documents a generic route and administrative rules. It does not identify a Romanian consignment.','US diplomatic records')
source('S15','State Department’s position on foreign-mint gold','Fred M. Dearing to S. P. Gilbert Jr.','1921-04-09','English','Contemporary financial record','Full published document read','https://history.state.gov/historicaldocuments/frus1921v02/d729','FRUS 1921, vol. II, doc. 729; file 861.51/1002','Discusses title, friendly-country mint marks, and why Treasury must decide what the US mints accept.','Not a certificate that particular gold had clean title, nor proof of Romanian gold in Swedish bars.','US diplomatic records')
source('S16','The S.S. Carmania gold shipment rejected at New York','S. P. Gilbert Jr. to the Secretary of State','1921-08-11','English','Contemporary financial record','Full published document read','https://history.state.gov/historicaldocuments/frus1921v02/d732','FRUS 1921, vol. II, doc. 732; file 861.51/1257','Records 7,500 imperial gold roubles consigned by the Bank of England to J. P. Morgan & Co.; the New York Assay Office rejected the tender on 10 August.','No Romanian provenance is stated. This is a negative control against turning every Soviet gold shipment into “the Romanian treasure.”','US diplomatic records')
source('S17','Romanian memorandum alleging gold reaching the United States','Romanian Legation to the US Department of State','1921-08-15','English','Contemporary diplomatic allegation','Full published memorandum read','https://history.state.gov/historicaldocuments/frus1921v02/d733','FRUS 1921, vol. II, doc. 733; file 871.51/251','Romania alleged that part of the gold reaching the US was its 1916 deposit being used for Soviet payments abroad.','The memorandum names no ship, bank, weight, assay lot or informant. Authentic evidence of an allegation, not authentication of a shipment.','Romanian diplomatic allegation')
source('S18','Boyle, Joseph Whiteside','William Rodney, Dictionary of Canadian Biography','Vol. XV (1921–1930)','English','Scholarly biography','Full relevant article read','https://www.biographi.ca/en/bio/boyle_joseph_whiteside_15E.html','Moscow mission, December 1917; bibliography at end','Explicitly distinguishes Boyle’s recovery of archives and paper currency from later claims about bullion and crown jewels.','Retrospective scholarship. The precise contents should ultimately be checked against mission and receiving inventories.','Boyle historiography')
source('S19','British Adventurers and Revolutionary Russia’s War over Bessarabia','Geoffrey Swain, Revolutionary Russia','2021-11-30','English','Scholarly article','Full open-access PDF obtained; relevant passages read','https://eprints.gla.ac.uk/257366/1/257366.pdf','34:2, pp. 219–238; DOI 10.1080/09546545.2021.1996320; notes 8, 42, 44','Locates Boyle material in PRONI D1943 and British diplomatic papers; retells a jewels claim through George Hill’s memoir.','Its introductory shipment summary repeats problematic quantities. A memoir-derived jewel story is not a BNR gold recovery manifest.','Boyle historiography')
source('S20','Queen Marie of Romania papers — finding aid','Kent State University Special Collections','Collection: 1918–1991 and related material','English','Archive finding aid','Relevant catalogue sections read','https://speccoll.library.kent.edu/women/marie/queen.html','Box 1; subseries 1D on Boyle and the Romanian treasure','Identifies correspondence and later investigations, including 1946 and 1990 material, useful for tracing how the rescue legend developed.','A catalogue is not the correspondence itself. Much is decades later than the events; no inspected 1917 treasure notebook here.','Kent catalogue')
source('S21','Bucarest, légation puis ambassade, 1916–1980 — finding aid','Archives diplomatiques, France','Archival fonds 124PO/1','French','Archive finding aid','Full finding aid obtained; relevant entries read','https://archivesdiplomatiques.diplomatie.gouv.fr/media/f946dbd5-6453-4454-ae85-e85feaf49c2d.pdf','124PO/1, articles 63–64, 66–67; relevant list around p. 14','Locates Russian/Romanian correspondence and French military-mission records for the critical custody and diplomatic period.','Underlying files not inspected. Series relevance does not prove a treasure document is inside. Early wartime destruction also creates gaps.','French diplomatic catalogue')
source('S22','Din presa vremii: Glasul Bucovinei despre Tezaurul românesc, 1920','Ion N. Oprea, Luceafărul','2021-04-09','Romanian','Period-press transcription','Modern transcription read; original issues not inspected','https://luceafarul.net/din-presa-vremii-glasul-bucovinei-despre-tezaurul-romanesc-1920','Glasul Bucovinei no. 465, 10 July 1920; also nos. 453, 474, 558; cites Oprea’s 2008 book, pp. 115–116','Transcribes a report alleging Romanian 20-lei coins pledged in Danish banks, attributed to an unnamed Copenhagen newspaper.','A multi-step quotation chain. The Danish newspaper, banks, coin lots and original Romanian scan remain unidentified or unread.','1920 press allegation')
source('S23','Glasul Bucovinei digitized collection','LIBRARIA, Ukrainian periodicals archive','Issues listed: 1918–1941','Romanian / Ukrainian catalogue','Newspaper catalogue','Collection record read; target issue not inspected','https://libraria.ua/en/all-titles/group/934/','Target: no. 465, 10 July 1920; alternative collection at adt.arcanum.com','A concrete route to obtaining the original newspaper behind the Danish-bank allegation.','Listing coverage does not establish that this exact issue is accessible without an account or subscription.','Periodical catalogue')
source('S24','Tezaurul României la Moscova după 1989: Odiseea continuă','Historia','2020-10-19','Romanian','Journalistic investigation','Relevant full web article read','https://historia.ro/sectiune/general/tezaurul-romaniei-la-moscova-dupa-1989-odiseea-567198.html','Private schemes and the 12-coin donation narrative','Reports twelve French and Belgian coins, total 77.09 g, connected to a private arrangement and a 2008 museum donation.','Museum accession documentation and original custody proof were not obtained. Genuine nineteenth-century coins do not establish origin in the Moscow deposit.','2008 donation reporting')
source('S25','The Romanian National Bank Treasure Taken to Moscow and Never Returned','Cristian Păunescu; foreword Mugur Isărescu; Oscar Print','2020','English','Book','16-page opening preview read','https://oscarprint.ro/wp-content/uploads/2020/10/Tezaur-bnr-paginat.pdf','ISBN 978-973-668-529-3; calendar note p. 3; opening account pp. 13–16','Useful calendar warning and account of the diplomatic pressure preceding evacuation.','Not the complete book. Older quantity and value conventions should not override the current fine-gold claim without reconciliation.','Romanian official claim')
source('S26','Tezaurul român de la Moscova (1934) — located edition','Mihail Gr. Romașcanu; modern Ziaristi Online presentation','1934; web presentation 2019-03-10','Romanian','Book discovery','Book located; full text not obtained','https://www.ziaristionline.ro/2019/03/10/victor-roncea-dosarul-moscova-2-nu-aduce-nimic-nou-totul-despre-tezaurul-roman-de-la-moscova-prima-si-cea-mai-importanta-investigatie-din-1934-a-lui-mihail-romascanu-pdf/','1934 documentary compilation; embedded third-party copy','Important early compilation to compare with later inventories and retellings.','The surrounding website is not the book. No claim here is based on pretending the embedded book was read.','Bibliographic lead')
source('S27','The Gold Treasure of National Bank of Romania from Moscow between history and politics','Nadia Manea','2025','English abstract / Romanian scholarship','Scholarly article','Abstract and DOI record read','https://doi.org/10.59277/aicsus.32.09','DOI 10.59277/aicsus.32.09','Recent synthesis distinguishes the 91.5-tonne reserve from identity/cultural treasure and discusses the 2024 resolution.','Full article not obtained; abstract only. Substantially draws on the same official and Schipor evidence families.','Romanian official claim')
source('S28','A new strategy for recovery of the Romanian treasure','Radio România Actualități','2026-04-30','English','Current news','Full relevant web article read','https://www.romania-actualitati.ro/news-in-english/a-new-strategy-for-the-recovery-of-the-romanian-treasure-sent-to-moscow-in-1916-and-1917-id227709.html','Reporting on a proposed memorandum and strategy','Shows the recovery issue remained active in 2026.','A proposed strategy is not a signed return agreement, shipment or recovered gold.','Current Romanian policy')
source('S29','Russian response to the European Parliament’s gold demand','RBC, reporting Maria Zakharova’s statements','2024-03-15','Russian','News / official counterclaim','Relevant web text read','https://www.rbc.ru/politics/15/03/2024/65f363339a79475d9b264d14','Response on debt offsets, returns and Soviet-era claims','Documents Russia’s public counter-position and its use of broader historical financial claims.','Political assertions are not itemized custody records. No audited ledger is supplied to establish that the BNR reserve was repaid.','Russian official counterclaim')
source('S30','Claim that Russia offered the treasure back and Romania refused','Veridica','2026-04','English','Fact-check','Relevant web text read','https://www.veridica.ro/en/fake-news-disinformation-propaganda/fake-news-the-russians-wanted-to-return-romanias-treasure-but-romania-refused','Amsterdam/private-return narrative','Examines a circulating story of a refused private return arrangement.','A fact-check is not an archive inspection. No authenticated current holding or inventory was found through this story.','Current rumor analysis')
source('S31','Rușii au găsit, în propriile arhive, documente despre Tezaurul României (I)','Ilie Schipor; Cetatea Cavalerilor article reprinted by ActiveNews','2024-03-15','Romanian','Research article / reconstructed table','Written article and inventory-table image inspected','https://www.activenews.ro/cultura-istorie/Colonel-Dr.-Ilie-Schipor-RUSII-AU-GASIT-IN-PROPRIILE-ARHIVE-DOCUMENTE-DESPRE-TEZAURUL-ROMANIEI-I-Ce-valoare-avea-si-ce-continea-TABEL-188165','Table headed “Numărul de: lăzi / saci”; discussion of Mosyakin’s 2021 volumes','Reconstructs the first shipment by denomination: German marks 45.56%, Austrian crowns 29.31%, Romanian caroli 0.34% of stated BNR value.','An author’s modern table, not the original ledger. Values and case rows reconcile; its Austrian row says 4,397 bags, versus 4,387 in the BNR annex photograph and transcription (S41–S42). The latter reconciles the printed 13,823 total. Host commentary is not endorsed.','Schipor archival reconstruction')
source('S32','Золото Российской империи и большевики. 1917–1922 гг.','Aleksandr G. Mosyakin; Mezhdunarodnye otnosheniya','2021','Russian','Book / facsimile collection','Publisher record and search excerpts; full volumes not read','https://imobook.ru/book/istoriya-istoricheskie-nauki/Zoloto-Rossijskoj-imperii-i-bolsheviki','Three volumes; ISBN 978-5-7133-1649-5; publisher advertises 742 documents','Potential independent access path to RGAE facsimiles cited in Schipor’s later comparison.','Publisher’s broad political framing is not a finding. Preview download timed out; exact Romanian entries and shelfmarks require the volumes.','Mosyakin collection lead')
source('S33','British test case concerning Soviet gold','US Ambassador George Harvey','1921-07-14','English','Contemporary financial record','Published XML document read','https://history.state.gov/historicaldocuments/frus1921v02/d731','FRUS 1921, vol. II, doc. 731; file 861.51/1205','Context for the 7,500-rouble shipment later recorded on the Carmania.','A Russian bondholder and Russian gold case, not an established Romanian claim.','US diplomatic records')
source('S34','Tezaurul României de la Moscova prin noi documente ruse și sovietice','George Popescu / Radio România Actualități, with Ilie Schipor','2021-06-14','Romanian','Radio / written research summary','Written article read; broadcast not transcribed','https://www.romania-actualitati.ro/emisiuni/istorica/tezaurul-romaniei-de-la-moscova-prin-noi-documente-ruse-si-sovietice-id152899.html','Istorica programme article','Contemporary account of the new Russian-archive research and why it changed the disappearance narrative.','The same Schipor work, not a separate archive audit.','Schipor archival reconstruction')
source('S35','Romanian Treasure','Wikipedia contributors','Accessed 2026-09-05','English','Reference overview','Web text read','https://en.wikipedia.org/wiki/Romanian_Treasure','Starting article and bibliography','A useful starting index of names, returns and popular explanations.','The approximately 120-tonne wording is not the current fine-gold claim. This investigation does not rely on Wikipedia as decisive evidence.','Reference overview')
source('S36','Alexandru Lapedatu — publications and archive references','Lapedatu family foundation','Undated page','Romanian','Bibliographic guide','Relevant web page read','https://www.lapedatu.com/?page_id=28','Bibliography and memoir links','Provides a discovery route to the published diary and further Lapedatu material.','A guide, not an additional independent eyewitness.','Lapedatu bibliography')
source('S37','The Odyssey of the Romanian treasure taken to Moscow','Ion Jinga / Romanian Permanent Representation to the Council of Europe','2024 context','English','Official essay','Extended search excerpts read','https://coe.mae.ro/en/local-news/1655','Historical narrative and older 93.452-tonne figure','Useful record of official advocacy and a competing published quantity convention.','Not fully fetched. Do not silently reconcile its older quantity or wagon count with newer official figures.','Romanian official claim')
source('S38','The expulsion of the Romanian Legation','US Ambassador David R. Francis','1918-01-29','English','Contemporary diplomatic record','Full published document read','https://history.state.gov/historicaldocuments/frus1918Russiav02/d832','FRUS 1918, Russia vol. II, doc. 832','Independent contemporary record of the diplomatic rupture surrounding seizure.','Does not inventory the treasure.','US diplomatic records')
source('S39','Romania: from 1880 to 1947','George Virgil Stoenescu, Adriana Aloman, Elisabeta Blejan and Brîndușa Grațiela Costache; hosted by BNR','Historical monetary study; online chapter','English','Scholarly monetary-history chapter','Full PDF obtained; monetary-standard section read','https://www.bnr.ro/uploads/editor/425471817.pdf','Chapter VI; section 1.2, printed pp. 244–247; monetary-standard table','Documents 0.3226 g of mint gold at 900‰ per leu, and 3,100 lei per kg of 900‰ gold. Also describes removal of the Moscow deposit from note-cover stock in 1929.','A monetary-history synthesis, not an assay of the treasure. Removing an asset from currency-cover calculations does not prove physical repayment or legal discharge.','Romanian monetary-history scholarship')
source('S40','Сводка о наличии ценностей на 1 февраля 1922 г.','Commission for accounting and concentration of valuables; published in a 2018 document edition','Not earlier than 1922-02-01; edition 2018','Russian','Published contemporary accounting record','Catalogue and published-document web transcription read','https://docs.historyrussia.org/ru/nodes/73089','Document 236, printed p. 391; RGASPI f. 19, op. 1, d. 492, l. 108; certified-copy description','A concrete Soviet accounting comparison distinguishes usable coin, defective coin, bullion/scrap and valuable objects, producing different totals as categories are added. It is a useful control on what a gold balance means.','The inspected account does not identify a Romanian component. Its 217.2 / 218.4 / 244.9-million-rouble totals must not be substituted for a Romanian inventory or used to resolve Pokivaylova’s two Romanian-specific balances. Archive original not inspected.','Published Soviet accounting record')

source('S41','First-shipment inventory annex and selected protocol facsimiles','National Bank of Romania, publishing Russian/French deposit records','1917-02-16 (document date)','Russian / French','Primary-document facsimile','Four selected photographs visually inspected','https://www.bnr.ro/uploads/editor/984499206.jpg','Annex image 984499206.jpg; protocol first page 1266638180.jpg, last page 210295509.jpg; operations annex 220870989.jpg, linked from S42','The summary annex visibly gives 4,387 Austrian-crown bags and a total of 13,823 bags. Selected protocol pages identify parties, seals, guards and a four-copy document arrangement.','Selected institutional photographs, not a complete protocol or an archive visit. The Romanian-coin lei-value cell appears to read 1,065,000, while its currency amount and the official transcription give 1,065,705; the latter reconciles the grand total. Do not describe every original cell as independently reconciled. No 1921 or 1924 original is supplied here.','Romanian official archive')
source('S42','Inventarul tezaurului / Treasure inventory','National Bank of Romania','Undated current page; inspected 2026-09-05','Romanian / English','Official inventory transcription','Both rendered language versions read; linked scans inspected','https://www.bnr.ro/24779-inventarul-tezaurului','English counterpart: https://www.bnr.ro/en/24934-treasure-inventory; denomination table and final paragraph','Official table uses 4,387 Austrian-crown bags. Romanian text places the additional four gold cases in summer 1917. The reserve is described as 91.5 tonnes of fine gold.','English final paragraph says December 1917 for the additional four cases, unlike Romanian summer 1917 and the history chronology. This is a language-version inconsistency, not evidence for a third shipment. The table is a transcription and has to be distinguished from the facsimile.','Romanian official claim')
source('S43','Treasure history','National Bank of Romania','Undated current page; inspected 2026-09-05','English','Official chronology','Rendered substantive page read','https://www.bnr.ro/en/24933-treasure-history','Shipment and restitution chronology','Direct institutional source for the two shipment values, August 1917 additional deposit, and return accounts.','Its stated total 315,179,980.41 gold lei is 25,000 above its stated components. This discrepancy is therefore present on BNR itself, not merely in a newspaper reprint. Institutional summaries are not infallible; originals should control.','Romanian official claim')

timeline=[]
def event(id,date,year,title,track,status,body,limits,refs):
    timeline.append(dict(id=id,date=date,year=year,title=title,track=track,status=status,body=body,limits=limits,sources=refs.split()))
event('T01','Autumn 1916',1916,'A state retreats; a reserve becomes vulnerable','context','Documented context','Romania’s military reverses drove the government and central bank to Iași. Evacuation was a response to a real threat, not a treasure expedition. Russian pressure and guarantees enter the documentary story before shipment.','A later Soviet seizure does not by itself establish a single premeditated plan stretching back through the imperial government.','S03 S06 S25')
event('T02','14 / 27 December 1916 (OS / NS)',1916,'The first deposit agreement','gold','Officially documented','The first shipment comprised 1,738 BNR cases and two cases of Queen Marie’s jewels. The bank’s stated value was 314,580,456.84 gold lei; the jewels were separately valued at 7 million.','We read published descriptions, the official table and selected original-document photographs, not the complete protocol and every annex. Do not turn the jewellery valuation into literal bullion weight.','S03 S25 S31')
event('T03','Late December 1916 OS / early January 1917 NS',1917,'The consignment reaches Moscow','gold','Officially documented','The first deposit was placed in the Russian State Bank’s Kremlin treasury facilities, commonly identified with the Armoury Palace. Verification continued into February.','Published arrival dates differ by a day or more as well as by calendar. The site preserves a window rather than manufacturing a precise unified date.','S03 S04 S25')
event('T04','16 February 1917 (source date)',1917,'An inventory becomes the reference fingerprint','gold','Officially documented','The inventory and protocol recorded the first shipment’s contents. Later comparisons need its denominations, case numbers, weights and signatures—not merely “Romanian gold” as a label.','Calendar normalization varies across retellings. BNR’s annex photograph resolves the modern table’s ten-bag discrepancy: 4,387 Austrian-crown bags, not 4,397.','S04 S07 S31 S41 S42')
event('T05','21–27 July 1917 OS / 3–9 August NS',1917,'Packing the country’s cultural memory','cultural','Eyewitness diary','Lapedatu describes instructions, packing, George Enescu manuscripts, paintings, inspections, repeated delays and guards. On 27 July he records unloading, inspection, reloading and sealing.','His charge was a subset of the cultural shipment, not all bank bullion or every institution’s property. Printed diary pp. 117–119.','S11')
event('T06','27 July / 9 August 1917',1917,'A second agreement, not another 90 tonnes','gold','Officially documented','The BNR component comprised 188 cases of mixed assets. Additional gold was valued at 574,523.57 gold lei—about 167 kg at the historical parity, commonly rounded to 170 kg. Much larger aggregate values included paper assets and institutional property.','The frequently quoted billions of lei for the second train are not billions of lei of physical gold.','S03 S04 S25')
event('T07','28 July / 10 August 1917',1917,'Lapedatu’s train actually departs','cultural','Eyewitness diary','The diary records departure from Iași at 2 p.m., crossing the Prut later that day. The next entries place the party at Chișinău and Bender, then farther north and east.','Signing on 27 July and departure on 28 July are distinct events. Published summaries sometimes collapse them. Printed pp. 118–119.','S11')
event('T08','29 July–3 August OS / 11–16 August 1917 NS',1917,'Follow the observed railway stops','cultural','Eyewitness diary','Entries name Chișinău, Bender, Cherkasy, Pryluky, Bryansk and Moscow. Moscow arrival is recorded on 3 August around 10 p.m., followed by a guarded overnight stop.','A projected route mentioned earlier in the diary is not identical to the observed route. Map lines connect observations, not verified railway track geometry. Printed pp. 119–120.','S11')
event('T09','5 / 18 August 1917',1917,'Two kinds of treasure, different rooms','gold','Officially documented','The additional BNR gold was recorded as deposited with the earlier reserve at the Kremlin. Cultural consignments had their own storage arrangements and later moves.','Do not apply every cultural-storage episode to the bank’s reserve.','S03 S11')
event('T10','5–26 August OS / 18 August–8 September 1917 NS',1917,'A damp room, then a documented relocation','cultural','Eyewitness diary','Lapedatu found ministry crates in a cramped, damp room beneath guard stairs and sought relocation. Later entries describe trucks, rain, the move to the Ssudnaia Kazna and checks on paintings. He counted 142 cases below, 38 on the ground floor and three above within his charge.','Those 183 cases are not the national shipment total. The diary reports an inspected painting crate dry; damp premises are not proof that all contents were destroyed. Printed pp. 121, 129–130.','S11')
event('T11','October–December 1917 (diary dates)',1917,'Plans to send treasure to America','cultural','Eyewitness diary','The diary records anxiety about protection, a consular report after fighting, and proposals to move Academy cases via an American train. By late November the cases were to remain in Moscow.','Proposed evacuation is not completed shipment. No recovered American receipt was found. Printed pp. 142, 151, 155–158.','S11')
event('T12','December 1917',1917,'Boyle brings back records and currency','cultural','Retrospective reconstruction','Joseph Boyle’s mission brought archives and paper currency out of revolutionary Russia. A major scholarly biography explicitly rejects the bullion-and-crown-jewels embellishment; another article repeats a jewel story through Hill’s memoir.','No inspected gold manifest proves that Boyle recovered the BNR reserve. Jewel claims require separate object-level reconciliation.','S18 S19 S20')
event('T13','13 / 26 January 1918',1918,'Seizure becomes policy','gold','Officially documented','The Soviet authorities broke relations and declared the Romanian gold inaccessible to the Romanian oligarchy, while promising to preserve it for the Romanian people. US diplomatic reports in the following days independently document the rupture and gold dispute.','This is evidence of deliberate retention, not of an unrecorded disappearance at the moment of revolution.','S01 S03 S12 S13 S38')
event('T14','January 1918; reconstructed in 1921 records',1918,'Paper currency removed','cultural','Published archival reconstruction','Moisuc, citing Schipor documents 60 and 63, describes sixteen cases of Romanian banknotes taken by Commissioner Fritsche.','Banknotes are not gold. Using this episode to prove bullion financed revolutionary operations would change the asset category. Moisuc p. 72.','S09')
event('T15','February 1919, according to a 1924 report',1919,'A separate lead for the royal diamonds','cultural','Published archival reconstruction','The translated retrospective report says Ganetsky took royal-family brilliants and some banknotes from the Kremlin deposit.','This account conflicts with simple versions of the Boyle-jewels rescue. Original report, jewellery lists and receiving records are still required.','S09 S18 S19')
event('T16','Autumn 1919',1919,'Gold is reportedly divided by currency','gold','Published archival reconstruction','The 1924 report describes British pounds, Turkish lira and German marks sent toward “Samara–Tashkent”; Austrian crowns in 548 cases and German marks in 77 cases sent to Perm; French francs, Romanian money and other currencies left in Moscow.','This is a later report reproduced through translation. “Samara–Tashkent” is an ambiguous destination or route label, not proof of a specific surviving Tashkent vault.','S05 S09')
event('T17','10 July 1920',1920,'A Copenhagen rumor enters the Romanian press','gold','Unverified contemporary allegation','A modern transcription of Glasul Bucovinei no. 465 reports gold—allegedly mainly Romanian 20-lei coins—pledged in Danish banks, citing an unnamed Copenhagen paper.','Original issue, Danish source and bank ledgers not inspected. Coin type alone cannot establish the Moscow deposit as origin.','S22 S23')
event('T18','5 September–1 October 1920',1920,'The accounting trail deserves attention','gold','Published archival reconstruction','Pokivaylova discusses Lenin’s request to Alsky to count the gold fund, and a report due by 1 October. Schipor’s later article describes a 1 October memorandum recording Romanian gold.','The full original accounts have not been read here. Pokivaylova’s 2021 statement that an Alsky report was classified is not a verified present-day access ruling.','S10 S31')
event('T19','25 March and 9 April 1921',1921,'A documented international gold pathway','context','Contemporary primary record','US Treasury and State correspondence explains how gold with Swedish mint stamps was treated differently from visibly Soviet-origin gold. This gives a concrete records trail to examine.','Generic Soviet-gold handling, not an identified Romanian shipment. The mint book and matched export/assay entries are missing.','S14 S15')
event('T20','23 May 1921',1921,'The crucial proposed inventory match','gold','Researcher’s claim to audit','Schipor says an RGAE report matches the 1917 deposit by denomination and proves the reserve intact at this date. If sustained by the original annexes, this sharply weakens earlier total-loss stories.','We have read his account, not independently performed the complete comparison. Bookkeeping continuity must also be distinguished from a physical recount.','S07 S31')
event('T21','July 1921',1921,'Reported return of evacuated gold to Moscow','gold','Published archival reconstruction','Schipor’s publisher summary places the return of evacuated Romanian gold to Kremlin stores in July 1921. The later report describes overseas disposal after return.','Obtain movement vouchers and receiving receipts to check which portions returned and when.','S05 S09')
event('T22','10–11 August 1921',1921,'A real ship—and a crucial non-identification','context','Contemporary primary record','The New York Assay Office rejected 7,500 imperial gold roubles tendered by J. P. Morgan & Co., consigned from the Bank of England on the Carmania.','The record says Russian gold, not Romanian-deposit gold. Its proximity to the next memorandum is not proof they concern the same consignment.','S16 S33')
event('T23','15 August 1921',1921,'Romania formally alleges US-bound disposal','gold','Contemporary allegation in a primary record','The Romanian Legation told the State Department that some gold arriving in the United States came from the 1916 Moscow deposit and was being used for Soviet payments abroad.','The memorandum supplies no shipment identifiers. It also precedes the autumn-1921 start in Schipor’s summary: an unresolved timing tension, not a reason to rewrite either source.','S17 S05')
event('T24','1 January 1922; reports in February',1922,'Gold still appears in the accounts','gold','Published archival reconstruction','Pokivaylova cites Romanian gold in Soviet holdings at the start of 1922, but gives different balances from Osokina and Sirotkin. She points to Sokolnikov’s February reports to Lenin.','The two values—105,102,337.88 and 87,074,501.05 gold roubles—must not be averaged into a fictional inventory. Scope, date and asset definitions need checking.','S10')
event('T25','1921–1923',1923,'Cultural deposits are opened and inventoried','cultural','Published archival reconstruction','Published Russian and Romanian research describes commissions, movements of cases and museum/archive inventories. These create a separate, potentially item-identifiable trail.','Commission totals and packing cases are not interchangeable with the original 1917 cases. Underlying lists remain a priority.','S09 S10')
event('T26','13 December 1924',1924,'The best route clue points into finance','gold','Published archival reconstruction','The translated report says French francs, British pounds and German marks were sent almost entirely abroad in installments under Narkomfin; Austrian crowns went to the State Bank’s Issue Section.','No foreign recipient list is supplied in the passage. The Russian original and annexes are necessary before assigning particular banks or countries.','S09')
event('T27','1924–early 1925',1925,'Loss of separate identity, not necessarily disappearance of metal','gold','Convergent published interpretations','Pokivaylova describes the gold as обезличено by 1924; Schipor places final depletion by early 1925. Together they favor absorption or dispersal over an intact hidden reserve.','The authors differ in explanations and numerical claims. “Depersonalized” can concern accounting identity; complete physical melting is not established by that word.','S05 S08 S10')
event('T35','1929 monetary stabilization',1929,'An accounting change is not a recovery','context','Published monetary history','A BNR-hosted monetary history says the Moscow deposit was removed from the bank’s note-cover stock in the 1929 monetary reform.','This concerns the assets qualifying as currency cover. It is not a receipt showing the gold came back, nor by itself a legal discharge of the deposit claim.','S39')
event('T28','31 May–27 June 1935',1935,'First major return: inspect what came back','cultural','Officially documented','The handover protocol listed 1,443 cases/bales and 27 folders/packages. Cargo traveled Moscow → Odesa → S.S. Principesa Maria → Constanța → Bucharest. BNR received 212 cases of notes, printing supplies, securities and records.','These were not 1,443 gold cases. No BNR reserve was returned. Original deposit seals and a one-to-one crate identity cannot be assumed.','S03 S04 S10')
event('T29','6–22 August 1956',1956,'Art and historical objects return','cultural','Officially documented','A protocol was signed on 6 August; two trains reached Bucharest on 14 and 15 August. The often-cited total is 39,320 objects, including Pietroasele, paintings, coins and medals. An exhibition opened on 22 August.','33,068 coins does not mean 33,068 gold coins. Reported gold within returned objects exceeded 33 kg, not 91.5 tonnes of reserve. Published category totals differ by two objects.','S03 S04 S10')
event('T30','September 1965',1965,'A communist Romania asks again','context','Published historical record','Romania raised the bank reserve with Soviet leaders. Published accounts describe Soviet resistance and attempts to join the question to broader financial offsets.','Diplomatic positions neither establish a present location nor independently settle the legal validity of offsets.','S09 S10')
event('T31','2003–2019',2019,'A commission, not a recovered consignment','context','Officially documented','The 2003 treaty framework led to a joint historical commission, first meeting in 2004. The 2024 resolution records five meetings, the last in 2019, and a 2016 acknowledgement of authentic deposit documents.','Recognition of documents and unsuccessful talks should not be reported as a return agreement.','S01 S03')
event('T32','6 March 2008, reported retrospectively',2008,'Twelve coins offer a bounded provenance test','gold','Unverified provenance claim','Reports describe twelve French/Belgian coins totaling 77.09 g donated to MNIR, linked to a private return scheme.','The accession and donation files have not been obtained. The coins’ age, authenticity and Moscow-deposit provenance are different questions.','S24')
event('T33','14 March 2024',2024,'Europe asks for restitution','context','Official primary record','The European Parliament adopted its resolution calling for return of the Romanian treasure and identifying 91.5 tonnes of fine gold.','Nonbinding political resolution; not a locating operation or enforceable judgment in itself.','S01')
event('T34','24 October 2025–30 April 2026',2026,'New documentation and proposed strategy','context','Current institutional reporting','BNR launched a document portal in October 2025. Radio România reported a proposed recovery strategy in April 2026.','No authenticated recovery or current physical holding was identified in the sources inspected for this case file. This is a research finding, not proof that no undisclosed material exists.','S02 S03 S28')
timeline.sort(key=lambda x:x['year'])

exhibits=[
dict(id='E01',title='The number on the case label',status='Strong official basis',question='Are we looking for 120 tonnes?',finding='Use approximately 91.5 metric tonnes of fine gold for the BNR monetary reserve. Keep the royal jewels, cultural objects, securities and private property in separate ledgers.',detail='The European Parliament’s 2024 resolution and the newer BNR material use 91.5 tonnes. Older descriptions give 93.4, 93.452 or roughly 120 tonnes, sometimes without a consistent asset boundary. We have not proved a single gross-to-fine conversion that explains all variants.',next='Reconcile the original 1917 weight columns, fineness and gold-lei values before adopting any more precise mass.',sources=['S01','S03','S25','S35','S37']),
dict(id='E02',title='A notebook puts us on the train',status='Published eyewitness account',question='Can we follow someone who was actually there?',finding='Yes. Lapedatu’s Moscow diary supplies observed stops, packing and storage incidents, including the departure a day after the second protocol.',detail='Use printed pp. 117–121 and 129–130 (PDF pages +4). His projected route and actual entries diverge. His cultural cases later moved to the Ssudnaia Kazna; this must not be represented as movement of the entire gold reserve.',next='Compare the published diary with the manuscript and railway/consular receipts. Preserve the diary’s Julian dates alongside converted dates.',sources=['S11','S36']),
dict(id='E03',title='The reserve had many nationalities',status='Official transcription and selected facsimile checked',question='Would a Romanian coin identify the treasure?',finding='No. The inspected first-shipment table assigns only 0.34% of BNR value to Romanian caroli. German marks and Austrian crowns together account for about 75%.',detail='The official transcription sums to 314,580,456.84 gold lei, 1,738 bank cases and 13,823 bags. The annex photograph confirms 4,387 Austrian-crown bags; the modern reprint has 4,397. The Romanian-coin value cell in the photograph also needs comparison with its currency column and official transcription. Value share is not measured mass share.',next='Extend this selected-image check to all original annexes, then compare the May 1921 inventory. Preserve transcription differences rather than silently repairing them.',sources=['S31','S41','S42']),
dict(id='E04',title='The revolution did not erase all paperwork',status='Contemporary diplomatic evidence',question='Was it simply mislaid in October 1917?',finding='The 1918 documents show deliberate official retention and an immediate diplomatic dispute.',detail='US diplomatic reports in late January and early February provide contemporary evidence independent of modern treasure stories. They do not settle what happened to the gold afterward, but contradict a narrative of nobody knowing who had it.',next='Trace the change from sealed foreign deposit to Soviet financial control through signed orders and custody books.',sources=['S12','S13','S38','S01']),
dict(id='E05',title='The May 1921 checkpoint',status='High-priority claim to independently audit',question='Did the reserve survive the civil-war years intact?',finding='Schipor says the 23 May 1921 report matches the 1917 inventory. If the complete comparison survives scrutiny, early total-loss theories become difficult to maintain.',detail='We have the author’s explicit argument, not the full original inventory with all entries and annexes. A balance carried forward on paper would be weaker than a physical stocktake. The audit must distinguish the two.',next='Acquire the RGAE report, inventory annex and methodology; compare currency, quantity, weight, case marks and signatures row by row.',sources=['S07','S31','S05']),
dict(id='E06',title='A 1924 report describes the exit',status='Archival document through two publication layers',question='Where does the strongest route clue lead?',finding='Toward Narkomfin’s foreign payments and Gosbank’s Issue Section, not a discovered underground cache.',detail='Moisuc quotes Schipor’s document 121, pp. 339–340: a report dated 13 December 1924 describes currency-specific relocation in 1919 and subsequent transfers abroad. We have inspected Moisuc’s pp. 73–74, not the original Russian folios. The quoted numerical expression “117,800,000 + 118,000,000” is ambiguous and is not treated as a sum.',next='Obtain document 121 in the full book, then its original file, adjacent folios and disposal annexes. Look for recipients and voucher numbers.',sources=['S09','S05']),
dict(id='E07',title='The American allegation is real; the shipment is not yet identified',status='Primary record of an allegation',question='Did Romanian gold reach the United States?',finding='Romania formally alleged this on 15 August 1921. The published memorandum does not prove which gold it was.',detail='File 871.51/251 has no named ship, receiving bank, mass, assay number or source of intelligence. Its date is earlier than the autumn-1921 expenditure start in Schipor’s summary. That tension is an investigative task, not a detail to smooth away.',next='Request the surrounding diplomatic file and intelligence behind the memorandum; then match actual customs, Treasury and assay entries.',sources=['S17','S05']),
dict(id='E08',title='The tempting ship-name trap',status='Verified generic shipment; Romanian link unproved',question='Was the Carmania carrying this treasure?',finding='The ship carried a documented Russian-gold consignment, but the inspected record does not identify it as Romanian.',detail='On 10 August 1921 the New York Assay Office rejected a tender of 7,500 imperial gold roubles consigned by the Bank of England to J. P. Morgan & Co. A nearby Romanian protest in the same FRUS section is not evidence that the two records describe the same cargo.',next='Use this as a control: require a shared lot identifier or custody document before connecting the cases.',sources=['S16','S17','S33']),
dict(id='E09',title='What does обезличено actually establish?',status='Translation boundary',question='Does “depersonalized” mean every coin was melted?',finding='Not necessarily. It can mean the gold lost its separately identified status; physical melting requires additional evidence.',detail='Pokivaylova p. 132 cites a 1924 account and then contrasts scholars who infer melting with Osokina’s more cautious possibility of only part being melted. The cited account is GARF f. 374, op. 28, d. 861, l. 91. We have read the book, not that original folio.',next='Read the full Russian accounting entry and trace transfers, mint batches and stock classifications. Do not translate an interpretation into a physical event.',sources=['S10']),
dict(id='E10',title='Returned gold objects are not returned bank reserves',status='Strong institutional distinction',question='Does the 1956 return close the case?',finding='No. Pietroasele and other gold-bearing historical objects returned, but the BNR reserve was not included.',detail='The BNR reprint reports 33,068 coins of unspecified metals, not 33,068 gold coins. More than 33 kg of gold was present in returned objects. This is a different ownership and inventory category from 91.5 tonnes of monetary gold.',next='Compare each institution’s 1917 inventory with 1935 and 1956 receipt registers to identify specifically missing objects.',sources=['S03','S04','S10']),
dict(id='E11',title='The twelve-coin test',status='Specific, unverified provenance lead',question='Could 77.09 grams be a surviving sample?',finding='Possibly, but published claims do not yet establish a chain from the 1916 deposit to the museum.',detail='The reported 2008 donation involves twelve French and Belgian coins. Reported identifiers include accession 867 and donation 1272; these are search leads from reporting, not catalogue entries we have verified. Even a genuine coin of the right date is a common object unless a continuous custody link distinguishes it.',next='Ask MNIR for the accession record, donor declaration, photographs, expert report and any documents linking the coins to a Russian treasury release.',sources=['S24']),
dict(id='E12',title='A newspaper clue with three missing links',status='Unverified period-press allegation',question='Do Danish banks provide an earlier export trail?',finding='A July 1920 Romanian press report, quoted in 2021, alleged Romanian 20-lei coins pledged in Denmark.',detail='The original Romanian issue has not been inspected. Its purported Copenhagen source is unnamed and no bank is specified. This is still useful: it supplies a narrow date window and a claim that could be corroborated or disproved.',next='Inspect Glasul Bucovinei no. 465, identify the Danish newspaper it used, then look for bank, shipment and lot details before any financial attribution.',sources=['S22','S23'])
]

hypotheses=[
dict(id='H01',title='An intact reserve still hidden in Moscow',assessment='Weakly supported',pro='The initial deposit and Soviet retention are well evidenced. Some cultural holdings remained identifiable for decades.',against='Published Russian-archive research describes movements, foreign disposal and loss of separate identity by the mid-1920s. No inspected current inventory, vault receipt or recent witness establishes an intact 91.5-tonne holding.',test='A verifiable current stock record linked to the 1917 deposit, supported by independent inspection. A vague “Moscow” label is insufficient.',sources=['S01','S05','S09','S10']),
dict(id='H02',title='Absorbed and dispersed through Soviet finance',assessment='Best-supported working explanation',pro='The translated 1924 report names overseas disposal by currency and domestic transfers to the Issue Section. Pokivaylova independently discusses 1922 balances and 1924 depersonalization.',against='Exact disposal dates, complete quantities and recipients remain unaudited here. The full original reports are missing; published authors disagree on balances and mechanism.',test='Reconcile the 1917, 1919, 1921, 1922 and 1924 records with outgoing vouchers, foreign bank receipts and mint ledgers.',sources=['S05','S07','S09','S10']),
dict(id='H03',title='Taken with Kolchak’s gold or by the Czech Legion',assessment='Romanian linkage unproven',pro='Imperial Russian gold really moved east and parts were captured, spent or lost. Pokivaylova discusses possible Romanian connections.',against='Her Romanian linkage is explicitly tentative; the cited Czech report itself relies on material of uncertain origin. No inspected manifest joins these cargos to the Romanian deposit. A sustained 1921 inventory match would weaken an early total loss.',test='A contemporaneous transfer receipt identifying Romanian case marks or a unique denomination/weight match, not merely foreign coins among Russian gold.',sources=['S10','S07']),
dict(id='H04',title='All melted or used for Brest-Litovsk payments in 1918',assessment='Poor fit with later reported inventories',pro='Soviet Russia exported gold and reminting could erase identifying features. Those general processes were real.',against='Later reported Romanian balances and the proposed May 1921 match contradict disappearance of the whole reserve in 1918. General Russian gold exports do not identify Romanian ownership.',test='Specific 1918 release and mint/payment records that identify the Romanian deposit, reconciled against later balances.',sources=['S07','S09','S10','S14']),
dict(id='H05',title='Scandinavian processing and Western buyers',assessment='Plausible route; Romanian consignments not yet matched',pro='US records directly describe Swedish-mint gold handling. Romania alleged US-bound disposal in August 1921; a 1920 press claim points to Denmark.',against='Neither inspected allegation identifies a proven Romanian lot. The Carmania file is Russian-gold evidence only. A mint stamp does not establish prior ownership.',test='Match a Russian outgoing voucher, Scandinavian receipt/melt number and Western assay or bank entry by date, mass and identifiers.',sources=['S14','S15','S16','S17','S22']),
dict(id='H06',title='Boyle recovered the reserve or all the royal jewels',assessment='Reserve claim unsupported; jewel story disputed',pro='Boyle’s successful recovery mission is historical, and Hill’s memoir inspired dramatic accounts.',against='The Dictionary of Canadian Biography explicitly excludes bullion and crown jewels. A later published Russian report places royal brilliants in a 1919 removal. These are not reconciled object lists.',test='Compare Boyle’s cargo and Romanian receiving lists with the two 1916 royal cases and the 1919 removal inventory.',sources=['S18','S19','S09','S20']),
dict(id='H07',title='The reserve was already repaid through later returns or offsets',assessment='Not demonstrated by inspected records',pro='Cultural returns occurred in 1935 and 1956; Russian officials invoke other debts, reparations and financial transfers.',against='Official Romanian inventories and the European Parliament distinguish those returns from the BNR gold. Counterclaims about debt do not themselves identify a reserve repayment or a legally agreed setoff.',test='An authenticated settlement instrument plus itemized receipt or discharge of this specific deposit obligation.',sources=['S01','S03','S04','S10','S29']),
dict(id='H08',title='A private intermediary can deliver a surviving cache now',assessment='No authenticated current holding found',pro='There are recurring private-return stories and a reported twelve-coin donation worth testing.',against='No inspected stock list, independent custodian confirmation or continuous provenance supports an available cache. Old coins and elaborate stories are not enough.',test='Verify the custodian and inventory first, then documentary provenance and independent inspection. Do not let an unverified sample authenticate a much larger promised holding.',sources=['S24','S30'])
]

leads=[]
def lead(id,title,priority,goal,basis,request,success,stop,access,refs):
    leads.append(dict(id=id,title=title,priority=priority,goal=goal,basis=basis,request=request,success=success,stop=stop,access=access,sources=refs.split()))
lead('L01','Obtain the decisive Russian document set','A · Highest information value','Establish the reserve’s last separately identifiable custody and the first documented disposal.','Schipor’s 1919/1921 comparison and document 121 are central; the full book and original archive annexes were not obtained.','Please identify and provide research copies, including annexes and adjacent folios, for the gold inventory dated 14 August 1919, the RGAE report of 23 May 1921, and the report of 13 December 1924 reproduced as document 121, pp. 339–340, in Ilie Schipor, Destinul Tezaurului României (2021). Please include complete archive shelfmarks and any outgoing-voucher references.','Authentic facsimiles with complete identifiers; a reproducible denomination/weight comparison; named recipients or voucher numbers.','A summary repeating the author’s conclusion without tables or original references does not complete this lead.','Publisher/library access first; then holding archives. No purchase or request was made.','S05 S06 S07 S09 S31 S32')
lead('L02','Audit GARF’s 1924 “depersonalized” entry','A · Highest information value','Determine what обезличено meant in this specific account.','Pokivaylova p. 132 cites GARF f. 374, op. 28, d. 861, l. 91.','Прошу уточнить возможность получения исследовательской копии: ГА РФ, ф. 374, оп. 28, д. 861, л. 91, включая оборот и соседние листы, относящиеся к румынскому золоту. Просьба сообщить заголовок дела, дату документа, автора и наличие приложений о движении золота.','A complete entry that distinguishes accounting consolidation, physical remelting and actual transfers; references to follow-on documents.','Do not infer a melting date from the isolated word. Check that the cited folio actually supports the claim and whether its citation has shifted.','Shelfmark is as cited in a published book; catalogue and current access status not independently confirmed. Russian request is a working draft.','S10')
lead('L03','Recover the intelligence behind the US memorandum','A · Highest information value','Turn an authentic Romanian allegation into a testable shipment claim.','FRUS 1921 II, doc. 733, file 871.51/251, dated 15 August 1921.','Please identify the complete file and associated enclosures behind the Romanian Legation memorandum of 15 August 1921, State Department decimal file 871.51/251, published as FRUS 1921, volume II, document 733. We seek the source of the allegation, follow-up correspondence and any named ships, banks, customs entries or assay lots. Please confirm the modern series and box reference.','An enclosure or reply naming a lot, bank, ship or informant, which can be independently checked.','If the file only repeats rumor and contains no identifiers, retain it as a contemporary allegation and reduce its priority.','US National Archives / Office of the Historian discovery route. A modern box number has not been established; the decimal file is real.','S17')
lead('L04','Match Soviet exports to Swedish mint and Western receipts','A · Conditional on a shipment identifier','Test a physical gold route across three independent institutions.','US Treasury documents explain Swedish mint-stamp treatment; the 1924 translated report says coins went abroad.','For a matched 1921–1924 date and lot, seek Narkomfin dispatch and insurance vouchers, Swedish mint receiving and melt books, export records, and the destination bank or assay-office receipt. Record date, gross/fine mass, denomination, sender, recipient, batch number and account. Do not start by assuming every Soviet lot was Romanian.','A three-way match with a Romanian origin identifier before remelting, and a continuous financial or physical chain afterward.','No Romanian link means a generic Soviet-gold route, not a discovery. Stop attributing once continuity is lost; describe that loss explicitly.','Exact Swedish repository series not yet established. Use official mint/Riksbank/archive catalogues; no bank was contacted.','S09 S14 S15 S17')
lead('L05','Follow the Austrian crowns into the Issue Section','A · Distinct domestic path','Avoid assuming every coin went overseas.','The 1924 report separately says Austrian crowns went to the State Bank’s Issue Section; the first-shipment table attributes about 29.31% of BNR value to Austrian crowns.','Request the State Bank Issue Section receiving ledgers and Narkomfin transfer orders for Austrian gold crowns from Romanian deposits, 1921–1925. Seek original treasury/case references, denomination totals, valuation basis and any subsequent reclassification or minting instructions.','A receiving entry matched to the Romanian-origin outgoing record and a subsequent disposition.','A generic Austrian-crown balance is insufficient: this currency circulated widely.','Repository and series must be established from the original 1924 report’s references.','S09 S31')
lead('L06','Reconcile cultural objects one by one','A · Best prospect for identifiable surviving objects','Produce a defensible missing-object register, distinct from monetary gold.','MNIR’s 2016 announcement identifies National Art Museum return-inventory registers exhibited from the 1956 restitution. Lapedatu documents specific cultural shipments.','Vă rog să indicați inventarele de expediție din 1917 și registrele de primire din 1935 și 1956 pentru bunurile evacuate la Moscova. Pentru fiecare obiect neidentificat, căutăm numărul de inventar vechi și nou, descrierea, fotografia, dimensiunile, materialul, instituția deținătoare și eventualele procese-verbale de transfer. Solicitarea este pentru cercetare documentară, nu pentru inițierea unei revendicări.','An object-level difference list with images and stable identifiers; subsequent museum or sale records that can be checked.','A difference in crate counts is not a missing-object list. Exclude documented returns and items never shipped.','MNIR, National Art Museum, Academy and depositing institutions. Registers located by description; underlying pages not yet obtained. Romanian text is a working draft.','S03 S04 S09 S10 S11')
lead('L07','Test the twelve-coin donation at MNIR','B · Bounded and potentially inexpensive','Determine whether any small physical sample has documentary Moscow provenance.','Reporting describes 12 French/Belgian coins, 77.09 g, donated on 6 March 2008; reported references 867 and 1272 require confirmation.','Vă rog să confirmați existența și cotele dosarului donației din 6 martie 2008 privind 12 monede de aur franceze și belgiene, cu masa totală relatată de 77,09 g. În presă apar numerele 867 și 1272, neconfirmate de noi. Căutăm fișele de inventar, declarația de proveniență, expertiza, fotografiile și orice document care leagă monedele de depozitul românesc din Moscova din 1916–1917.','A museum-confirmed accession plus documents bridging Russia and the donor; separate expert findings on coin authenticity and provenance.','If only the donor’s assertion links them to Moscow, label provenance unproven. Do not extrapolate 12 coins to the full reserve.','No museum file inspected or request sent.','S24')
lead('L08','Identify the Danish newspaper behind the July 1920 claim','B · Bounded press trail','Move one step closer to the earliest alleged Western disposal.','Glasul Bucovinei no. 465, 10 July 1920, as quoted by Oprea; digitized collection located.','Obtain the complete issue, including neighboring columns, corrections and following issues. Transcribe the Copenhagen attribution exactly. Search Danish papers in the preceding weeks for rumænsk guld, rumænske guldmønter, 20 lei, russisk guld and Romanian/Roumanian variants; only then identify banks and their records.','Original report with named source and, ideally, bank or shipment identifiers; a correction or retraction is equally valuable.','An unsourced chain of repeated press stories remains one allegation, however many newspapers printed it.','LIBRARIA / Arcanum collection located; exact issue not inspected, account access may be needed.','S22 S23')
lead('L09','Separate Boyle’s cargo from his legend','B · Resolve conflicting testimony','Establish exactly which records, banknotes and jewels were recovered in 1917.','Rodney rejects bullion/jewels; Swain retells a Hill-derived jewels account; the 1924 report mentions royal brilliants in 1919.','Request the relevant December 1917 mission and cargo records in the Boyle papers cited as PRONI D1943/1–3, particularly receiving lists and Romanian acknowledgements. Compare with Hill’s Go Spy the Land (1932), chapters 15–20, the two royal cases in 1916, and any 1919 removal inventory. Confirm catalogue references before ordering.','A cargo list and signed receiving record, cross-matched to identifiable royal objects or to paper-only cargo.','A memoir anecdote or later congratulatory letter cannot independently identify the contents of a sealed royal case.','PRONI reference is from Swain; original file catalogue not independently checked. Kent’s finding aid locates later correspondence, not proof of a rescue.','S18 S19 S20 S09')
lead('L10','Trace French protective custody and keys','B · Fill the 1918 handover gap','Clarify who could access the deposits after diplomatic rupture.','French diplomatic finding aid identifies relevant correspondence and military-mission series.','Je recherche les pièces relatives à la garde des dépôts roumains à Moscou en 1917–1918, notamment la remise des clefs, les scellés, les inventaires et les protestations diplomatiques. L’instrument de recherche 124PO/1 mentionne les articles 63–64 et 66–67. Pourriez-vous confirmer les dossiers pertinents et leurs conditions de consultation, sans présumer que ces articles contiennent les pièces recherchées ?','A dated handover or access record naming the deposit and responsible persons; independent comparison with Romanian and Russian copies.','Holding keys is not the same as physical control if guards or authorities changed. Do not infer continuous secure custody from a diplomatic title.','French finding aid inspected; underlying files not read. Draft not sent.','S21 S12 S13')
lead('L11','Check the 1922 balance discrepancy','B · Numerical reconciliation','Determine whether apparently conflicting figures use different dates or asset boundaries.','Pokivaylova p. 132 quotes 105,102,337.88 gold roubles from Osokina and 87,074,501.05 from Sirotkin; p. 131 cites February reports.','Obtain Osokina, Zoloto dlia industrializatsii, p. 364; Sirotkin, Zarubezhnoe zoloto Rossii, p. 305; and the Sokolnikov reports cited as RGASPI f. 5, op. 1, d. 1372, ll. 3–8. Transcribe dates, headings, unit definitions and whether values are physical stock, book balances or net available funds.','A explained difference grounded in complete documents, or a documented error in one secondary account.','Do not average the balances, convert them into an exact tonnage without basis, or select the figure that best supports a favored theory.','Books and original folios not obtained in this session. Shelfmarks are published citations, not confirmed current retrieval entries.','S10')
lead('L12','Require a Romanian identifier before chasing eastern hoards','C · Only after stronger records justify it','Keep the Kolchak/Czech/Japan trail falsifiable and bounded.','General Russian gold traveled east; a Romanian component is speculative in the inspected literature.','First obtain an outgoing Romanian-deposit record naming Kazan, a captured train, Czech custody or an eastern bank, or find a receiving record with matching case identifiers. Only then expand to Czech military finance, Vladivostok shipping, Japanese or Chinese bank archives.','A specific bridge from this deposit into that custody chain.','Without the bridge, do not commission a field search, assume a lake/train story is relevant, or describe general Imperial gold as Romanian property.','No physical search target or verified present holding has been identified.','S10 S07')

coins=[
dict(label='German marks',cases=726,bags=5801,goldLei=143321750,share=45.56),
dict(label='Austrian crowns',cases=550,bags=4387,goldLei=92188488,share=29.31),
dict(label='Napoleons / French-franc group',cases=288,bags=2304,goldLei=46117140,share=14.66),
dict(label='British pounds',cases=111,bags=885,goldLei=22357076.04,share=7.11),
dict(label='Ottoman lira',cases=48,bags=377,goldLei=8604996.82,share=2.74),
dict(label='Romanian caroli',cases=7,bags=52,goldLei=1065705,share=0.34),
dict(label='Russian coins (n, as printed)',cases=2,bags=13,goldLei=370085.80,share=0.12),
dict(label='Gold ingots',cases=3,bags=None,goldLei=337247.80,share=0.11),
dict(label='Various coins',cases=1,bags=None,goldLei=103605.12,share=0.03),
dict(label='Russian coins (v, as printed)',cases=1,bags=4,goldLei=101298.40,share=0.03),
dict(label='Iron chest (as printed)',cases=1,bags=None,goldLei=13063.86,share=0.01)
]

glossary=[
dict(term='Tezaur / treasure',text='May mean the bank reserve, royal jewels, cultural heritage, securities or the entire evacuation. Always identify the asset category.'),
dict(term='Aur fin / чистое золото / fine gold',text='Pure-gold content, not necessarily the gross weight of alloyed coins or their containers. A monetary valuation is a third, distinct measure.'),
dict(term='Обезличено / obezlicheno',text='Depersonalized or no longer separately identified. In this case, accounting absorption and physical melting must not be assumed equivalent.'),
dict(term='Ссудная казна / Ssudnaia Kazna',text='Loan or deposit treasury; also rendered Sudnaia Kassa in secondary accounts. A cultural-storage location distinct from the BNR reserve’s initial Kremlin deposit.'),
dict(term='Наркомфин / Narkomfin / NKF',text='People’s Commissariat for Finance. Its dispatch and payment records are central to the proposed disposal trail.'),
dict(term='Госбанк / Gosbank',text='State Bank. The Issue or Emission Section is a distinct destination in the translated 1924 account of Austrian crowns.'),
dict(term='GARF / ГА РФ',text='State Archive of the Russian Federation. A cited shelfmark is not a verified current access permission.'),
dict(term='RGAE / РГАЭ',text='Russian State Archive of the Economy. Reported source of the May 1921 inventory and many Mosyakin facsimiles.'),
dict(term='RGASPI / РГАСПИ',text='Russian State Archive of Socio-Political History. Cited for Lenin/Sokolnikov correspondence and political decisions.'),
dict(term='Fond / opis / delo / list',text='Archive collection / inventory or series / file / folio. “Ob.” means verso. Record all levels and both sides when requesting copies.'),
dict(term='OS / NS',text='Old Style (Julian) / New Style (Gregorian). In 1916–1917, add 13 days when the original is actually Julian; do not convert an already normalized date again.'),
dict(term='Pietroasele / Pietroasa / Cloșca cu puii de aur',text='An identifiable ancient treasure returned in 1956, now associated with MNIR. Its return is not a return of the bank’s monetary reserve.'),
dict(term='Place-name aliases',text='Iași / Jassy; Chișinău / Kishinev; Bender / Tighina; Odesa / Odessa; Moscow / Moscova / Москва. Search historical spellings as well as modern ones.'),
dict(term='Person-name aliases',text='Schipor; Pokivaylova / Pokivailova / Покивайлова; Mosyakin / Mosiakin / Мосякин; Ganetsky / Ganețki / Ганецкий; Alsky / Alski / Альский.'),
]

data=dict(meta=dict(title='The Moscow Deposit',subtitle='Romanian Treasure · an open case file',version='1.1',cutoff='2026-09-05',scope='Desk investigation using publicly accessible and legitimately available material. No archive visit, paid acquisition, outreach or physical recovery.',language='English synthesis; Romanian, Russian, English and French sources; Danish search leads only.',copyright='Original summaries only. Third-party books and archive images are linked, not redistributed.'),sources=sources,timeline=timeline,exhibits=exhibits,hypotheses=hypotheses,leads=leads,coins=coins,glossary=glossary,chapters=json.loads((ROOT/'research'/'report_chapters.json').read_text()))
(ROOT/'site'/'data.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
print(f'{len(sources)} sources, {len(timeline)} events, {len(exhibits)} exhibits, {len(hypotheses)} hypotheses, {len(leads)} leads')
